### ISSUE TITLE
Automatic yes to prompts is missing

### ISSUE THREAD

**Issue by tobr-dev** [pietrobolcato/install-azure-cli-action#1]
apt-get install is aborted on my runner
please add there -y parameter
->
sudo apt-get install -y ca-certificates curl apt-transport-https lsb-release gnupg
sudo apt-get install -y azure-cli

**Comment by pietrobolcato** [comment]
Thank you so much for opening this issue! I will check it and update the code later today :)

**Comment by pietrobolcato** [comment]
Dear @tobr-dev, I created a bugfix branch where the issue should be solved.

Before I merge to main, could you please check if it works on your runner? You can call the updated workflow with:

```
uses: pietrobolcato/install-azure-cli-action@bugfix/issue-1/pending-installer
```

So for example:

```
name: test-azure-cli-installation
on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install azure cli
        uses: pietrobolcato/install-azure-cli-action@bugfix/issue-1/pending-installer
```

Thanks a lot!

**Comment by tobr-dev** [comment]
Hi @pietrobolcato 
you fixed `install_cli.sh` on 8th line however there is still missing -y switch on 3rd line
->
sudo apt-get install -y ca-certificates curl apt-transport-https lsb-release gnupg
Thanks :)

**Comment by tobr-dev** [comment]
I have prepared PR https://github.com/pietrobolcato/install-azure-cli-action/pull/2

That tobr-dev/install-azure-cli-action@patch-1 works for me.
BR.

**Comment by pietrobolcato** [comment]
Thanks a lot for the PR! I merged it :)

Closing this for now!
